version: "3.8"
services:
    mysql:
        ports:
            - "3306:3306"

    mailhog:
        container_name: mailhog
        image: mailhog/mailhog:latest
        ports:
            - "8025:8025"

    redis:
        ports:
            - "6379:6379"
