version: "3"
services:
    mysql:
        ports:
            - "3306:3306"
        container_name: mysql
        image: mysql:8.0
        working_dir: /application
        volumes:
            - ../:/application
            - ./data/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=$DB_PASSWORD"
            - MYSQL_DATABASE=parser

    nginx:
        container_name: nginx
        image: nginx:alpine
        working_dir: /application
        volumes:
            - ../:/application
            - "./nginx/config/dev/default.conf:/etc/nginx/conf.d/default.conf"
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./log/nginx:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"

    php:
        container_name: php
        build: php-fpm
        working_dir: /application
        volumes:
            - ../:/application
